tasks:
  - before: export FLASK_ENV=development
    init: pip install -r requirements.txt
    command: |
      flask run

  # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-preview
